<?php
/*array(菜单名，菜单url参数，是否显示)*/
$i=0;
$j=0;
$menu_left =  array();
$menu_left[$i]=array('全局','#',1);
$menu_left[$i]['low_title'][$i."-".$j] = array('全局设置','#',1);
//$menu_left[$i][$i."-".$j][] = array('欢迎页',U('/admin/index/home'),1);
$menu_left[$i][$i."-".$j][] = array('网站设置',U('/admin/global/websetting'),1);
//$menu_left[$i][$i."-".$j][] = array('友情链接',U('/admin/global/friend'),1);
//$menu_left[$i][$i."-".$j][] = array('地区管理',U('/admin/area/index'),1);
$menu_left[$i][$i."-".$j][] = array('广告管理',U('/admin/ad/index'),1);
//$menu_left[$i][$i."-".$j][] = array('会员级别管理',U('/admin/leve/index'),1);
//$menu_left[$i][$i."-".$j][] = array('会员年龄别称',U('/admin/age/index'),1);
//$menu_left[$i][$i."-".$j][] = array('登陆接口管理',U('/admin/loginonline/index'),1);
$j++;
$menu_left[$i]['low_title'][$i."-".$j] = array('在线通知管理','#',1);
$menu_left[$i][$i."-".$j][] = array('支付接口管理',U('/admin/payonline/index'),1);
$menu_left[$i][$i."-".$j][] = array('通知信息接口管理',U('/admin/msgonline/index'),1);
$menu_left[$i][$i."-".$j][] = array('通知信息模板管理',U('/admin/msgonline/templet/index'),1);
$j++;
$menu_left[$i]['low_title'][$i."-".$j] = array('缓存管理','#',1);
$menu_left[$i][$i."-".$j][] = array('前台模板',U('/admin/global/cleantemplet?acahe=1'),1);
$menu_left[$i][$i."-".$j][] = array('后台模板',U('/admin/global/cleantemplet?acahe=2'),1);
$menu_left[$i][$i."-".$j][] = array('会员中心',U('/admin/global/cleantemplet?acahe=3'),1);
$menu_left[$i][$i."-".$j][] = array('数据缓存',U('/admin/global/cleandata'),1);
$menu_left[$i][$i."-".$j][] = array('所有缓存',U('/admin/global/cleanall'),1);
$j++;
$menu_left[$i]['low_title'][$i."-".$j] = array('用户权限管理',"#",1);
$menu_left[$i][$i."-".$j][] = array('管理员管理',U('/admin/Adminuser/index'),1);
$menu_left[$i][$i."-".$j][] = array('用户组权限管理',U('/admin/acl/index'),1);
$menu_left[$i][$i."-".$j][] = array('管理员登录日志',U('/admin/Adminuser/loginlog'),1);
$menu_left[$i][$i."-".$j][] = array('人员操作日志',U('/admin/Adminuser/loglist'),1);
//$j++;
//$menu_left[$i]['low_title'][$i."-".$j] = array('文件管理','#',0);
//$menu_left[$i][$i."-".$j][] = array('文件管理',U('/admin/mfields/index'),1);
$j++;
$menu_left[$i]['low_title'][$i."-".$j] = array('数据库管理','#',1);
$menu_left[$i][$i."-".$j][] = array('数据库信息',U('/admin/db/index'),1);
$menu_left[$i][$i."-".$j][] = array('备份管理',U('/admin/db/baklist'),1);
//$menu_left[$i][$i."-".$j][] = array('清空数据',U('/admin/db/truncate'),1);
$i++;
$menu_left[$i]= array('项目管理','#',1);
$menu_left[$i]['low_title'][$i."-".$j] = array('项目列表','#',1);
$menu_left[$i][$i."-".$j][] = array('全部',U('borrow/waitverifyquanbu'),1);
$menu_left[$i][$i."-".$j][] = array('审核中',U('borrow/waitverify'),1);
$menu_left[$i][$i."-".$j][] = array('预热中',U('borrow/waitstart'),1);
$menu_left[$i][$i."-".$j][] = array('筹资中',U('borrow/waitmoney'),1);
$menu_left[$i][$i."-".$j][] = array('复审中',U('borrow/waitverify2'),1);
$menu_left[$i][$i."-".$j][] = array('已成功',U('borrow/repaymenting'),1);
$menu_left[$i][$i."-".$j][] = array('申请分红',U('borrow/applicationbouns'),1);
$menu_left[$i][$i."-".$j][] = array('已分红',U('borrow/done'),1);
$menu_left[$i][$i."-".$j][] = array('未成功',U('borrow/unfinish'),1);
$menu_left[$i][$i."-".$j][] = array('未通过',U('/admin/borrow/fail'),1);
$j++;
$menu_left[$i]['low_title'][$i."-".$j] = array('体验标管理','#',1);
$menu_left[$i][$i."-".$j][] = array('体验标管理',U('/Admin/borrow/edit?id=1'),1);
$j++;
$menu_left[$i]['low_title'][$i."-".$j] = array('联合种植','#',1);
$menu_left[$i][$i."-".$j][] = array('联合种植',U('/Admin/zhongzhi/index'),1);

$j++;
$menu_left[$i]['low_title'][$i."-".$j] = array('种植订单','#',1);
$menu_left[$i][$i."-".$j][] = array('种植订单',U('/Admin/orderz/index'),1);

$j++;
$menu_left[$i]['low_title'][$i."-".$j] = array('预售管理','#',1);
$menu_left[$i][$i."-".$j][] = array('预售管理',U('/Admin/ysgood/index'),1);


//$menu_left[$i][$i."-".$j][] = array('众筹分类',U('/admin/productcategory/index'),1);
// $menu_left[$i][$i."-".$j][] = array('复审未通过',U('/admin/borrow/fail2'),1);
// $j++;
// $menu_left[$i]['low_title'][$i."-".$j] = array('发布众筹','#',1);
// $menu_left[$i][$i."-".$j][] = array('发布众筹',U('/admin/release/add'),1);
// $menu_left[$i][$i."-".$j][] = array('众筹分类',U('/admin/productcategory/index'),1);
 
//$i++;
//
//$menu_left[$i]= array('积分商城','#',1);  
//$menu_left[$i]['low_title'][$i."-".$j] = array('产品管理','#',1);
//$menu_left[$i][$i."-".$j][] = array('产品管理',U('integralmall/index'),1);
//
//$j++;
// $menu_left[$i]['low_title'][$i."-".$j] = array('订单管理','#',1); 
// $menu_left[$i][$i."-".$j][] = array('订单管理',U('/admin/integralmall/ord'),1);
//  $j++;
// $menu_left[$i]['low_title'][$i."-".$j] = array('留言管理','#',1);
// $menu_left[$i][$i."-".$j][] = array('留言列表',U('/admin/comment/index'),1);
//  $j++;
// $menu_left[$i]['low_title'][$i."-".$j] = array('明细展示','#',1);
// $menu_left[$i][$i."-".$j][] = array('优秀项目排行',U('/admin/celebrity/project'),1);
// $menu_left[$i][$i."-".$j][] = array('优秀投资人排行',U('/admin/celebrity/investor'),1);
// $menu_left[$i][$i."-".$j][] = array('优秀分站排行',U('/admin/celebrity/index'),1);
// $menu_left[$i][$i."-".$j][] = array('经营项目排行',U('/admin/celebrity/index'),1);
// $menu_left[$i][$i."-".$j][] = array('分红项目排行',U('/admin/celebrity/index'),1);
 //$menu_left[$i][$i."-".$j][] = array('担保公司',U('/admin/guarantee/index'),1);
 //$menu_left[$i][$i."-".$j][] = array('担保公司分类',U('/admin/guartype/index'),1);
//$j++;
//$menu_left[$i]['low_title'][$i."-".$j] = array("债权转让","#",1);
//$menu_left[$i][$i."-".$j][] = array('债权转让',U('/admin/bond/index'),1);
//$j++;
//$menu_left[$i]['low_title'][$i."-".$j] = array('逾期借款管理','#',1);
////$menu_left[$i][$i."-".$j][] = array('逾期统计',U('/admin/expired/detail'),0);
//$menu_left[$i][$i."-".$j][] = array('已逾期借款',U('/admin/expired/index'),1);
//$menu_left[$i][$i."-".$j][] = array('逾期会员列表',U('/admin/expired/member'),1);
/*
$j++;
$menu_left[$i]['low_title'][$i."-".$j] = array('众筹管理','#',1);
$menu_left[$i][$i."-".$j][] = array('待初审的众筹',U('/admin/product/waitverify'),1);
$menu_left[$i][$i."-".$j][] = array('认购中的众筹',U('/admin/product/waitmoney'),1);
$menu_left[$i][$i."-".$j][] = array('还款中的众筹',U('/admin/product/repaymenting'),1);
$menu_left[$i][$i."-".$j][] = array('已完成的众筹',U('/admin/product/done'),1);
$menu_left[$i][$i."-".$j][] = array('发布众筹',U('/admin/product/add'),1);
*/
///$j++;
//$menu_left[$i]['low_title'][$i."-".$j] = array('众筹分类','#',1);
$i++;
$menu_left[$i]= array('会员管理','#',1);
$menu_left[$i]['low_title'][$i."-".$j] = array('会员管理','#',1);
$menu_left[$i][$i."-".$j][] = array('会员列表',U('/admin/members/index'),1);
//$menu_left[$i][$i."-".$j][] = array('会员资料列表',U('/admin/members/info'),1);
//$menu_left[$i][$i."-".$j][] = array('会员自动投标',U('/admin/members/auto'),1);
$menu_left[$i][$i."-".$j][] = array('推荐人列表',U('/admin/members/reclist'),1);
 $menu_left[$i][$i."-".$j][] = array('会员信息导出',U('/admin/memberimport/index'),1);
//$menu_left[$i][$i."-".$j][] = array('举报信息',U('/admin/jubao/index'),1);
$j++;
$menu_left[$i]['low_title'][$i . "-" . $j] = array('体验金管理', '#', 1);
// $menu_left[$i][$i . "-" . $j][]            = array('体验金发放列表', U('/admin/experience/index'), 1);
$menu_left[$i][$i . "-" . $j][]            = array('体验金发放', U('/admin/experience/pub'), 1);
$j++;
$menu_left[$i]['low_title'][$i . "-" . $j] = array('优惠券管理', '#', 1);
$menu_left[$i][$i . "-" . $j][]            = array('优惠券列表', U('/admin/bonus/index'), 1);
$menu_left[$i][$i . "-" . $j][]            = array('优惠券发放', U('/admin/bonus/add'), 1);
$menu_left[$i][$i . "-" . $j][]            = array('优惠券规则', U('/admin/bonus/rules'), 1);
$menu_left[$i][$i . "-" . $j][]            = array('过期提醒', U('/admin/bonus/guoqi'), 1);

//$j++;
//$menu_left[$i]['low_title'][$i."-".$j] = array('加息券管理','#',1);
//$menu_left[$i][$i."-".$j][] = array('加息券列表',U('/admin/memberinterest/index'),1);
//$menu_left[$i][$i."-".$j][] = array('加息券发放',U('/admin/memberinterest/add'),1);

$j++;
$menu_left[$i]['low_title'][$i."-".$j] = array('认证及申请管理','#',1);
$menu_left[$i][$i."-".$j][] = array('手机认证会员',U('/admin/verify_phone/index'),1);
//$menu_left[$i][$i."-".$j][] = array('视频认证申请',U('/admin/verify_video/index'),1);
//$menu_left[$i][$i."-".$j][] = array('现场认证申请',U('/admin/verify_face/index'),1);
//$menu_left[$i][$i."-".$j][] = array('VIP申请管理',U('/admin/vipapply/index'),1);
$menu_left[$i][$i."-".$j][] = array('会员实名认证申请',U('/admin/memberid/index'),1);
//$menu_left[$i][$i."-".$j][] = array('额度申请待审核',U('/admin/members/infowait'),1);
$menu_left[$i][$i."-".$j][] = array('上传资料管理',U('/admin/memberdata/index'),1);
$j++;
$menu_left[$i]['low_title'][$i."-".$j] = array('投资记录','#',1);
$menu_left[$i][$i."-".$j][] = array('日投资记录',U('/admin/investor/investorlist/?method=byday'),1);
$menu_left[$i][$i."-".$j][] = array('周投资记录',U('/admin/investor/investorlist/?method=byweek'),1);
$menu_left[$i][$i."-".$j][] = array('月投资记录',U('/admin/investor/investorlist/?method=bymonth'),1);
$menu_left[$i][$i."-".$j][] = array('总投资记录',U('/admin/investor/index'),1);
//$menu_left[$i][$i."-".$j][] = array('一月标投资记录',U('/admin/investor/investorlist/?method=byday1'),1);
//$menu_left[$i][$i."-".$j][] = array('二月标投资记录',U('/admin/investor/investorlist/?method=byday2'),1);
//$menu_left[$i][$i."-".$j][] = array('三月标投资记录',U('/admin/investor/investorlist/?method=byday3'),1);
/*$j++;
$menu_left[$i]['low_title'][$i."-".$j] = array('活动专区','#',1);
$menu_left[$i][$i."-".$j][] = array('活动专区',U('/admin/lottery'),1);
$menu_left[$i][$i."-".$j][] = array('活动设置',U('/admin/lottery/setting'),1);*/
//$j++;
//$menu_left[$i]['low_title'][$i."-".$j] = array('大转盘管理','#',1);
//$menu_left[$i][$i."-".$j][] = array('抽奖记录',U('/admin/zhuanpan/winlog'),1);
//$menu_left[$i][$i."-".$j][] = array('奖品列表',U('/admin/zhuanpan/index'),1);
//$menu_left[$i][$i."-".$j][] = array('奖品发布',U('/admin/zhuanpan/add'),1);
/*
$j++;
$menu_left[$i]['low_title'][$i."-".$j] = array('留言管理','#',1);
$menu_left[$i][$i."-".$j][] = array('留言列表',U('/admin/feedback/index'),1);
*/
$i++;
$menu_left[$i]= array('充值提现','#',1);
$menu_left[$i]['low_title'][$i."-".$j] = array('充值提现管理','#',1);
$menu_left[$i][$i."-".$j][] = array('充值记录',U('/admin/Paylog/index'),1);
$menu_left[$i]['low_title'][$i."-".$j] = array('充值管理','#',1);
$menu_left[$i][$i."-".$j][] = array('在线充值',U('/admin/Paylog/paylogonline'),1);
$menu_left[$i][$i."-".$j][] = array('网站充值导入',U('/admin/Pay/payimport'),1);
$menu_left[$i][$i."-".$j][] = array('线下充值',U('/admin/Paylog/paylogoffline'),1);
$menu_left[$i][$i."-".$j][] = array('充值记录总列表',U('/admin/Paylog/index'),1);
$j++;
$menu_left[$i]['low_title'][$i."-".$j] = array('提现管理','#',1);
$menu_left[$i][$i."-".$j][] = array('待审核提现',U('/admin/Withdrawlogwait/index'),1);

$menu_left[$i][$i."-".$j][] = array('提现申请',U('/admin/Withdrawlog/index'),1);
$menu_left[$i][$i."-".$j][] = array('审核通过,处理中',U('/admin/Withdrawloging/index'),1);
$menu_left[$i][$i."-".$j][] = array('已提现 ',U('/admin/Withdrawlog/withdraw2'),1);
$menu_left[$i][$i."-".$j][] = array('审核未通过',U('/admin/Withdrawlog/withdraw3'),1);
$menu_left[$i][$i."-".$j][] = array('提现申请总列表',U('/admin/Withdrawlog/index'),1);
$i++;
$menu_left[$i]= array('内容管理','#',1);
$menu_left[$i]['low_title'][$i."-".$j] = array('文章管理','#',1);
$menu_left[$i][$i."-".$j][] = array('文章列表',U('/admin/article/index'),1);
$j++;
$menu_left[$i]['low_title'][$i."-".$j] = array('文章分类','#',1);
// $menu_left[$i][$i."-".$j][] = array('内容管理',U('/admin/article/control'),1);
$menu_left[$i][$i."-".$j][] = array('文章分类',U('/admin/acategory/index'),1);

$i++;
$menu_left[$i]= array('资金统计','#',1);
$menu_left[$i]['low_title'][$i."-".$j] = array('会员帐户','#',1);
$menu_left[$i][$i."-".$j][] = array('会员帐户',U('/admin/capital_Account/index'),1);
$j++;
$menu_left[$i]['low_title'][$i."-".$j] = array('充值提现','#',1);
$menu_left[$i][$i."-".$j][] = array('充值记录',U('/admin/capital_Online/charge'),1);
$menu_left[$i][$i."-".$j][] = array('提现记录',U('/admin/capital_Online/withdraw'),1);
$j++;
$menu_left[$i]['low_title'][$i."-".$j] = array('会员资金变动记录','#',1);
$menu_left[$i][$i."-".$j][] = array('资金记录',U('/admin/capital_Detail/index'),1);
$j++;
$menu_left[$i]['low_title'][$i."-".$j] = array('网站资金统计','#',1);
$menu_left[$i][$i."-".$j][] = array('网站资金统计',U('/admin/capital_All/index'),1);

$j++;
$menu_left[$i]['low_title'][$i."-".$j] = array('客服管理','#',1);
$menu_left[$i][$i."-".$j][] = array('客服列表',U('/admin/kefu/index'),1);
$menu_left[$i][$i."-".$j][] = array('绑定客户',U('/admin/kefu/khlist'),1);

$menu_left[$i][$i."-".$j][] = array('客户统计',U('/admin/kefu/khindex'),1);
$menu_left[$i][$i."-".$j][] = array('未绑定客户',U('/admin/kefu/wkhlist'),1);

// $j++;
// $menu_left[$i]['low_title'][$i."-".$j] = array('客服客户统计','#',1);
// $menu_left[$i][$i."-".$j][] = array('客服客户统计',U('/admin/customer/index'),1);

$j++;
$menu_left[$i]['low_title'][$i."-".$j] = array('投资排名统计','#',1);
$menu_left[$i][$i."-".$j][] = array('日排名统计',U('/admin/ranking/ranklist/?method=byday'),1);
$menu_left[$i][$i."-".$j][] = array('周排名统计',U('/admin/ranking/ranklist/?method=byweek'),1);
$menu_left[$i][$i."-".$j][] = array('月排名统计',U('/admin/ranking/ranklist/?method=bymonth'),1);
$menu_left[$i][$i."-".$j][] = array('总排名统计',U('/admin/ranking/index'),1);
$menu_left[$i][$i."-".$j][] = array('项目种类统计',U('/admin/ranking/rankingcount'),1);
$menu_left[$i][$i."-".$j][] = array('项目投资统计',U('/admin/ranking/borrowcount'),1);
$j++;
$menu_left[$i]['low_title'][$i."-".$j] = array('待收排名统计','#',1);
$menu_left[$i][$i."-".$j][] = array('待收排名统计',U('/admin/daishou/index'),1);

   $i++;
   $menu_left[$i]= array('积分商城','#',1);
   $menu_left[$i]['low_title'][$i."-".$j] = array('商城商品管理','#',1);
   $menu_left[$i][$i."-".$j][] = array('商品管理',U('/admin/market/index'),1);
   $j++;
   $menu_left[$i]['low_title'][$i."-".$j] = array('兑换管理','#',1);
   $menu_left[$i][$i."-".$j][] = array('积分记录',U('/admin/market/getlog'),1);
   $menu_left[$i][$i."-".$j][] = array('兑换管理',U('/admin/order/order'),1);
   $menu_left[$i][$i."-".$j][] = array('退货申请',U('/admin/order/thorder'),1);
   $j++;
   $menu_left[$i]['low_title'][$i."-".$j] = array('赠品管理','#',1);
   $menu_left[$i][$i."-".$j][] = array('赠品管理',U('/admin/zengpin/index'),1);
   $j++;
   $menu_left[$i]['low_title'][$i."-".$j] = array('赠品处理','#',1);
   $menu_left[$i][$i."-".$j][] = array('赠品自提',U('/admin/zporder/index'),1);
   $menu_left[$i][$i."-".$j][] = array('赠品折现',U('/admin/zporder/zindex'),1);
   $menu_left[$i][$i."-".$j][] = array('赠品待处理',U('/admin/Myzengpin/index'),1);
   $j++;
   $menu_left[$i]['low_title'][$i."-".$j] = array('礼品管理','#',1);
   $menu_left[$i][$i."-".$j][] = array('礼品管理',U('/admin/yundan/index'),1);
   $j++;
   $menu_left[$i]['low_title'][$i."-".$j] = array('赠送赠品','#',1);
   $menu_left[$i][$i."-".$j][] = array('赠送赠品',U('/admin/Myzengpin/htindex'),1);
   $menu_left[$i][$i."-".$j][] = array('添加赠送',U('/admin/zengpin/htadd'),1);
   //农转转平台
   $i++;
   $menu_left[$i]= array('商品中心','#',1);
   $menu_left[$i]['low_title'][$i."-".$j] = array('商品管理','#',1);
   $menu_left[$i][$i."-".$j][] = array('商品管理',U('/admin/goods/index'),1);
   $menu_left[$i][$i."-".$j][] = array('商品分类',U('/admin/goods/typelist'),1);
   $j++;
   $menu_left[$i]['low_title'][$i."-".$j] = array('订单管理','#',1);
   $menu_left[$i][$i."-".$j][] = array('待付款',U('/admin/goods/order',array('id'=>0)),1);
   $menu_left[$i][$i."-".$j][] = array('已付款',U('/admin/goods/order',array('id'=>1)),1);
   $menu_left[$i][$i."-".$j][] = array('待收货',U('/admin/goods/order',array('id'=>2)),1);
   $menu_left[$i][$i."-".$j][] = array('已收货',U('/admin/goods/order',array('id'=>3)),1);
   $menu_left[$i][$i."-".$j][] = array('申请退款',U('/admin/goods/tuikuan'),1);
   $menu_left[$i][$i."-".$j][] = array('同意退款',U('/admin/goods/tongyi'),1);
//   $menu_left[$i][$i."-".$j][] = array('会员兑换管理',U('/admin/order/order'),1);
    $j++;
    $menu_left[$i]['low_title'][$i."-".$j] = array('合伙人管理','#',1);
    $menu_left[$i][$i."-".$j][] = array('未审核',U('/admin/goods/partner',array('id'=>0)),1);
    $menu_left[$i][$i."-".$j][] = array('通过审核',U('/admin/goods/partner',array('id'=>1)),1);
    $menu_left[$i][$i."-".$j][] = array('驳回审核',U('/admin/goods/partner',array('id'=>2)),1);

//    $i++;
//    $menu_left[$i]= array('拼团提现','#',1);
//    $menu_left[$i]['low_title'][$i."-".$j] = array('拼团提现','#',1);
//    $menu_left[$i][$i."-".$j][] = array('提现待审核',U('/admin/PttiAction/index'),1);
//    $menu_left[$i][$i."-".$j][] = array('提现已审核',U('/admin/PttiAction/index'),1);
//    $menu_left[$i][$i."-".$j][] = array('提现未通过',U('/admin/PttiAction/index'),1);


    $i++;
    $menu_left[$i]= array('拼团提现','#',1);
    $menu_left[$i]['low_title'][$i."-".$j] = array('拼团提现','#',1);
    $menu_left[$i][$i."-".$j][] = array('提现待审核',U('/admin/ptwithdrawal/index',array('status'=>0)),1);
    $menu_left[$i][$i."-".$j][] = array('提现已审核',U('/admin/ptwithdrawal/index',array('status'=>1)),1);
    $menu_left[$i][$i."-".$j][] = array('提现未通过',U('/admin/ptwithdrawal/index',array('status'=>2)),1);
   //拼团管理
   // $i++;
   // $menu_left[$i]= array('拼团管理','#',1);
   // $menu_left[$i]['low_title'][$i."-".$j] = array('商城商品管理','#',1);
   // $menu_left[$i][$i."-".$j][] = array('商品管理',U('/admin/market/index'),1);
   // $j++;
   // $menu_left[$i]['low_title'][$i."-".$j] = array('兑换管理','#',1);
   // $menu_left[$i][$i."-".$j][] = array('会员积分记录',U('/admin/market/getlog'),1);
   // $menu_left[$i][$i."-".$j][] = array('会员兑换管理',U('/admin/order/order'),1);

